### ISSUE TITLE
Garbage in what should be a source file resources/regions.json & discussion of cities1000.sqlite

### ISSUE THREAD

**Issue by jvonau** [iiab/maps#55]
https://github.com/iiab/maps/blob/master/resources/regions.json#L165

**Comment by holta** [comment]
Thanks @jvonau for catching this:

[regions.json](https://github.com/iiab/maps/blob/master/resources/regions.json#L165) needs a few fixes for sure.

**Comment by tim-moody** [comment]
unless @georgejhunt says otherwise the only required change is to disappear. Adm Cons can easily stop using it and I'm not sure that maps does anymore either. At least that's what I get from the readme, but I stand to be corrected.

**Comment by jvonau** [comment]
> unless @georgejhunt says otherwise the only required change is to disappear. Adm Cons can easily stop using it and I'm not sure that maps does anymore either. At least that's what I get from the readme, but I stand to be corrected.

If regions.json is unused then stop installing the file.

**Comment by holta** [comment]
I suspected as much, but thanks to everyone verifying the truth here!

(@georgejhunt can you confirm and/or mark this particular file as `regions.json.unused` &mdash; e.g. if this is indeed a legacy file with only documentation/historical value?)

**Comment by georgejhunt** [comment]
I cannot keep up with all the communication. No regions.json is not used.

**Comment by jvonau** [comment]
@georgejhunt I'll adjust my RPs accordingly. What about cities1000.sqlite?

**Comment by jvonau** [comment]
Mentions of:
[cities1000.sqlite](https://github.com/iiab/maps/search?q=cities1000.sqlite)
[regions.json](https://github.com/iiab/maps/search?q=regions.json)

**Comment by tim-moody** [comment]
cities is absolutely needed. it's the basis of search

**Comment by tim-moody** [comment]
on a VM with adm cons and osm already installed I removed
 /etc/iiab/regions.json
 /library/www/html/common/assets/regions.json 
/library/www/osm-vector-maps/maplist/assets/regions.json

in adm cons I selected San Jose tileset and installed (also did the base files)

no problems encountered

If I view maps with http://192.168.3.169/osm-vector-maps/viewer

I can get more details for San Jose than just above it

**Comment by jvonau** [comment]
> on a VM with adm cons and osm already installed I removed
 
/etc/iiab/regions.json <- installed with iiab in the role
/library/www/html/common/assets/regions.json <- [admin-console](https://github.com/iiab/iiab-admin-console/blob/4b2bc90ddefe39dcc164c8d147180d1a1dfffb9b/roles/common/tasks/main.yml#L159-L163)
/library/www/osm-vector-maps/maplist/assets/regions.json <- installed with iiab in the role

I've covered the removal in iiab within the ongoing PR.

**Comment by jvonau** [comment]
> cities is absolutely needed. it's the basis of search

That is what I thought also [osm-source/pages/viewer/searchapi.php](https://github.com/iiab/maps/blob/6ea9a0d4cf70fe66ea26eb06e7410e41e1aef75a/osm-source/pages/viewer/searchapi.php) uses it which is installed in the iiab role. It appears to be only needed to be generated once, but the tools to create the file have been marked as unused.

**Comment by tim-moody** [comment]
think it's a download from osm

**Comment by tim-moody** [comment]
I was referring to the source http://download.geonames.org/export/dump/

**Comment by tim-moody** [comment]
and yes we agreed to host it on github as per your PR

**Comment by tim-moody** [comment]
just want to be clear that we are inventorying someone else's file

**Comment by jvonau** [comment]
> just want to be clear that we are inventorying someone else's file

Think [mk-osm-min](https://github.com/iiab/maps/blob/d215c1e1dcfdfb475cf9f4e145bb0092e7444fca/tools.unused/mk-osm-min#L48-L60) covers from where and how cities1000.sqlite came into existence.
> Hosting ~26MB [cities1000.sqlite](http://download.iiab.io/content/OSM/vector-tiles/maplist/hidden/regional-resources/cities1000.sqlite) on GitHub is a fine idea (in my opinion anyway) even if in the past there were reasons that was highly discouraged.
> 
> Certainly the [iiab/maps](https://github.com/iiab/maps) repo and its history could hypothetically become bloated if in future big files like this accumulate + evolve — but that does not seem to be an immediate or insurmountable risk at this time.

git clones taking a long time for large files if I remember correctly, but with the role uses get_url, we are not cloning the repo.

**Comment by jvonau** [comment]
> I was referring to the source http://download.geonames.org/export/dump/

The cities1000.zip file forms only part of the source, it contains just a .txt file(no .sqlite), I think cities1000.sqlite was generated using mkfeatures.sql and geodb.pl from [tools.unused](https://github.com/iiab/maps/tree/master/tools.unused) then uploaded and reused ever since.

**Comment by tim-moody** [comment]
seems you are right. not sure if was refreshed when tiles were refreshed.

**Comment by georgejhunt** [comment]
I did not refresh cities1000.sql for the 2020 edition

**Comment by holta** [comment]
Many IIAB Maps design / infra layout questions carefully discussed during today's community call (http://minutes.iiab.io).

Great progress ongoing.

And we hope many testers over the coming week will help make this even shinier:

- iiab/iiab#3077
