### ISSUE TITLE
css issue current master

### ISSUE THREAD

**Issue by jvonau** [iiab/maps#57]
![Screenshot from 2022-04-28 23-03-19](https://user-images.githubusercontent.com/5579710/165884019-9b308953-02d5-4f9e-9c6d-efddef625c35.png)
> downloadable font: download failed (font-family: "Noto Sans" style:italic weight:400 stretch:100 src index:3): status=2147746065 source: http://192.168.122.35/osm-vector-maps/viewer/assets/noto-sans-v8-latin-italic.woff2

side by side diff of what is in iiab and what is in this repo #56, when fonts.css contains _**url('/common/fonts/**_ the above error is not present.
related https://github.com/iiab/iiab/pull/3198

**Comment by tim-moody** [comment]
Here is what I have in my current install

![image](https://user-images.githubusercontent.com/5678731/165949168-10e488bb-73f3-4d42-ad49-ff288443ebfe.png)

**Comment by tim-moody** [comment]
Here is what I had on Apr 6

![image](https://user-images.githubusercontent.com/5678731/165949513-06dfb216-c7f0-4b4c-bbf0-e9add5e114fc.png)

**Comment by holta** [comment]
> The first is without serif and the second has them.
> 
> The first question is which do we want. I assume the first.

Huge thanks for the screenshots & clarifying question.

@georgejhunt hopefully can steer us in the right direction?

**Comment by tim-moody** [comment]
The first is:

```
root@box:/opt/iiab/iiab# git log
commit 5b11dadd4950fafd09e1dc90949780ee37dc4bc9 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: A Holt <holta@users.noreply.github.com>
Date:   Thu Apr 28 12:24:19 2022 -0400

    Merge pull request #3192 from jvonau/osm_url

    host maps on github
```

except that I moved  all noto-sans font files

from /library/www/osm-vector-maps/viewer/assets/
to /library/www/html/common/fonts/

fonts.css remained in /library/www/osm-vector-maps/viewer/assets/

By whatever means. I think this is where the files belong.

**Comment by tim-moody** [comment]
@georgejhunt let's start with the desired behavior. Should the fonts used on the map be noto-sans or not?

>This is the smoking gun that removed fonts from viewer/assets

Isn't that what we want for noto-sans fonts on the map?

I think that:
/library/www/osm-vector-maps/viewer/index.html
loads  <link rel="stylesheet" href="./assets/fonts.css" type="text/css">
and assets/fonts.css declares the font files in
url('/common/fonts/noto-sans ...

So I think fonts.css belongs in /library/www/osm-vector-maps/viewer/assets
and the noto-sans font files belong in /library/www/html/common/fonts/

and that was the combination that produced my first screen shot.

**Comment by georgejhunt** [comment]
@timmoody, I agree with you.

**Comment by jvonau** [comment]
5b11dadd4950fafd09e1dc90949780ee37dc4bc9 installed fonts.css that contains url('/common/fonts/ from iiab into the correct location by fluke it's part of the source fonts directory that was installed. 

> Tim 'is it possible that the value of map branch affects this?' 

No that is the source of the fonts.css file, iiab vs maps, the one in iiab is correctly formatted but is installed in the different location(/library/www/html/common/fonts/).
The fonts.css from maps lacks the correct lines for the files on the iiab filesystem as that version is really intended for use within the git checkout with the fonts living in the same directory and should stay that way. 
However the maps version is being installed into the correct location(/library/www/osm-vector-maps/viewer/assets/). 
PR #3197 didn't alter the original location of where fonts.css from iiab is installed to, as not to introduce another unknown change but rather a link and omitting the version coming from the maps repo.
And over to you.

**Comment by holta** [comment]
Thanks @jvonau for the careful analysis and explanation.

> 5b11dadd4950fafd09e1dc90949780ee37dc4bc9

Clarif that's https://github.com/iiab/iiab/commit/5b11dadd4950fafd09e1dc90949780ee37dc4bc9 or:

- PR iiab/iiab#3192

**Comment by jvonau** [comment]
> > 5b11dadd4950fafd09e1dc90949780ee37dc4bc9
> 
> Clarif that's [iiab/iiab@5b11dad](https://github.com/iiab/iiab/commit/5b11dadd4950fafd09e1dc90949780ee37dc4bc9) or:
> 
>     * PR [host maps on github iiab#3192](https://github.com/iiab/iiab/pull/3192)

That git hash tells me that the git hash below was in use

[a784d5ec2758518e052b70d7d7e05e7546912063](https://github.com/iiab/iiab/pull/3192/commits/a784d5ec2758518e052b70d7d7e05e7546912063) placed the fonts in '/viewer/assets' based on the contents of the fonts.css from the maps repo. The surprise was iiab/fonts had it's own copy of fonts.css in the payload that I didn't know was there that lead to https://github.com/iiab/iiab/pull/3196 and the realization of the differences of the two versions and what needed to be done in https://github.com/iiab/iiab/pull/3197

**Comment by holta** [comment]
Thanks everyone for the very hard work pulling this together over recent weeks!
